### ISSUE TITLE
naming conventions

### ISSUE THREAD

**Issue by gabrielgellner** [ChrisRackauckas/DifferentialEquations.jl#3]
currently the packages, consistently :),  uses camelCase for naming, though common and fine, almost all julia packages have instead settled on using the (extremely rough) guidelines from the julialang `Contribuiting.md`

> # General Formatting Guidelines for Julia code contributions
> - 4 spaces per indentation level, no tabs
> - use whitespace to make the code more readable
> - no whitespace at the end of a line (trailing whitespace)
> - comments are good, especially when they explain the algorithm
> - try to adhere to a 92 character line length limit
> - use upper camel case convention for modules, type names
> - use lower case with underscores for method names
> - it is generally preferred to use ASCII operators and identifiers over Unicode equivalents whenever possible

even Jump, a package that used camelCase macros before this convention was decided upon has recently switched to be more consistent.

I know this is the most boring kind of discussion (bordering on things as silly as 0, 1 indexing, emacs vs vi etc). The only reason I think it is important is that it makes the julia ecosystem feel more consistent, and I have very high hopes that this package becomes the package for solving diff.eqs. (I kind of wish they had decided on camelCase ... as it feels far less ambiguous to me ... for example all the `issomething` vs `is_something` inconsistency, but the convention is the convention)

My favorite example of what happens when people don't all agree on this is the naming convention mess in R where fundamental functions like `read.table` have keyword arguments that mix `key.word` and `keyWord` styles within the same function! (not to mention I increasingly notice `key.word` vs `key_word` vs `keyWord` ... I am sure there are reasons but it is brutal as an end user).

If this is something you are willing to consider I am happy to help with the renaming ... as it will largely be busy work and testing.

**Comment by ChrisRackauckas** [comment]
Let's make this the official thread for formatting! I am completely open to formatting changes if it helps others.  

Here's my thought on those:

1. Sure, as Silicon Valley pointed out, spaces are obviously inferior to tabs, but if it makes people happy and matches other Julia code, I'll switch to spaces. I'll check if Atom be set to make tabs do 4 spaces.

2. I am using whitespace correctly. Yay!

3. Comments are good when necessary for describing little tricks in the code, but I think extra explanations should be in docstrings. Indeed, any new algorithms that aren't "well-known" should be cited in the docstrings. I think this is a better way to go because then, using Documenter.jl, it helps flesh out the documentation as well.

4. I'll fix the line limits. Honestly, I stopped doing it a bit because I was running into a bug. It turns out
```
a = 2 + 3 + 5 + 6
     + 7 + 8 + 9
```
silently incorrectly gives `a=16`, while
```
a = 2 + 3 + 5 + 6 +
      7 + 8 + 9
```
is correct. This is because of the way that the parser checks for expression endings. When I found that out, I started just first-drafting all the algorithms without care for line endings. Now that the vast majority of standard solvers are implemented with testing, I will go through and fix the line lengths to be reasonable.

5. My type names are the correct convention, but method names are not. That's a weird mix, but I'll make the change if that's what I'm supposed to do. I don't want to contribute to naming convention issues, even if I don't agree with them.

6. I am denying the last one. I WANT the internal solver codes to use unicode. I don't want to read math written out as mu, sigma, etc. in a programming language anymore. This is actually one of the things I like the most about Julia: the code looks like the math, and that makes it easier to write and maintain. If needed, I'll add a sheet to the documentation for the standard unicode symbols used in the solver, but anyone who has used LaTeX will know exactly what they are (except maybe mscO). However, I do agree that user-facing code should have less unicode to make it easier for newcomers.

**Comment by ChrisRackauckas** [comment]
Feel free to help with the renaming, line-spacing, white space, tabbing, etc. The only thing I am weary about is changing from unicode: please keep things unicode or let's discuss it case by case first (there shouldn't be many methods with unicode names).

Another thing that should be switched are the conditionals for the algorithm names. @ScottPJones pointed out to me that it's better to use symbols rather than strings, and I know JuMP is using symbols for choosing algorithms, so I'll switch to that. I (or someone) just needs to go to every if statement and swap them out, and then go through the mountain of tests to find them.

**Comment by gabrielgellner** [comment]
Yay! I agree with all of your points.

I really think the most important ones (in my opinion) is the naming of exported api (methods, types, variables) as this is what is forced on the end user. 

Line length requirements always feels so dodgy in this day and age to me since we largely have huge monitors ... but it people seem to care, I personally would prefer to see the sum you describe on one line, even if it goes over.

Agreed on unicode, I really like how you use \delta in the code etc. Again I feel the requirements on this point are stronger for Base then needed in this package, but if others chime in I have a soft preference for what you do.

P.S. it is easy for Atom to use spaces instead of tabs, I have never used tabs and it is seamless behind the scenes). Though again I have no real preference, this was just what I got used to from python.

**Comment by gabrielgellner** [comment]
For method keywords as symbols, I know that Optim.jl recently moved from symbols to using types after lengthy discussion. Again I have no real opinion on this (though symbol > string) but just in case you wanted to think about the kind of dispatch they have settled on as you seem to have a feel for the kind of API you are looking for.

**Comment by gabrielgellner** [comment]
I will start working on some renaming pull requests. Is it cool if I do it in stages? That is I will get the ode methods first etc. The only downside to this way of doing in is there will be a transition period were both conventions are used at once. The clear and obvious plus side is that it won't be a stupid huge pull request.

I will not change any unicode. I don't think this is an issue at all.

**Comment by ChrisRackauckas** [comment]
I was thinking about making a `State` abstract type, where then each conditional would check the state type. The state type would have some interface which has an internal dictionary to see if it's one of the allowed states, and throw an error otherwise. But I don't know of a really Julia way of implementing this and having it be lightweight (i.e. not carry that dictionary everywhere): maybe through multiple dispatch to some methods which check for errors and print messages? But this all seemed nice but not necessary for a first release (because I wouldn't want the users to make the State type anyways. I would want them to just pass a string/symbol, and do this all internally, so it makes no difference except making it easier to write error messages)

**Comment by ChrisRackauckas** [comment]
It's cool if it's in stages. Just make sure the tests pass. Right now the tests take quite awhile because they have to checkout Plots and RecipesBase. Once those get tagged with a new release, the tests will go back to around 20 minutes.

**Comment by gabrielgellner** [comment]
Sadly I am going to punt on this. I did some quick trials of moving over some public methods ... but between the tests, and the volume of code I realize that this is a much larger task than I had anticipated :( Maybe this package is just going to be a camelCase kind of world.

**Comment by ChrisRackauckas** [comment]
That's fine. I'll get to it soon. I think I need to get enough of this fixed up first anyways. It's still a ways off from being something "more public" for contribution. I mean, I'm going to pull out the individual solving algorithms to be function calls to match the suggestions of the julia-users thread and add in solvers from external packages, so I'll probably get to some code style fixes around then. The dust really hasn't settled in the internals at al.

**Comment by gabrielgellner** [comment]
No worries. I get that this is a work in progress. Just wanted to help! As it is a great project.

**Comment by ChrisRackauckas** [comment]
This is pretty much complete and will be merged over to this repo soon.
